[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
poolver = "Fz4KqVayYMmRyToZxJzErd9qRsnh8Bdq84yicvhv4114"

[programs.devnet]
poolver = "Fz4KqVayYMmRyToZxJzErd9qRsnh8Bdq84yicvhv4114"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "cargo test"

[hooks]
